-- PROFILES (lié à auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- WEIGHTS (historique de poids)
create table if not exists public.weights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  weight_kg numeric(5,2) not null check (weight_kg > 0),
  recorded_at date not null default (now()::date),
  created_at timestamptz not null default now(),
  unique (user_id, recorded_at)
);

-- PUSH SUBSCRIPTIONS (OneSignal)
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  onesignal_subscription_id text not null,
  platform text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, onesignal_subscription_id)
);

-- RLS
alter table public.profiles enable row level security;
alter table public.weights enable row level security;
alter table public.push_subscriptions enable row level security;

-- Policies : chaque utilisateur ne voit/modifie que ses lignes
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid());

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "weights_crud_own"
on public.weights for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "push_subscriptions_crud_own"
on public.push_subscriptions for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());