-- Phase 1 schema extensions for EvoShape

-- Extend profiles with Phase 1 fields.
alter table public.profiles
  add column if not exists sex text,
  add column if not exists birth_year int,
  add column if not exists height_cm int,
  add column if not exists target_calories int;

-- Meal templates for reusable meals.
create table if not exists public.meal_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  calories int not null,
  protein_g int,
  carbs_g int,
  fat_g int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Meal logs for daily tracking.
create table if not exists public.meal_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  recorded_at date not null default (now()::date),
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  template_id bigint references public.meal_templates(id) on delete set null,
  name text,
  calories int not null,
  created_at timestamptz not null default now()
);

-- Activity logs for daily activity tracking.
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  recorded_at date not null default (now()::date),
  activity_type text not null,
  duration_min int not null,
  calories_burned int not null,
  created_at timestamptz not null default now()
);

-- RLS
alter table public.meal_templates enable row level security;
alter table public.meal_logs enable row level security;
alter table public.activity_logs enable row level security;

-- Policies
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

create policy "meal_templates_crud_own"
on public.meal_templates for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "meal_logs_crud_own"
on public.meal_logs for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "activity_logs_crud_own"
on public.activity_logs for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Trigger to create profile after auth.users insert.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, created_at, updated_at)
  values (new.id, new.email, now(), now())
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
